Replace pkg_resources with importlib_metadata
ArangoDB-Community/python-arango pull request #250
Opened 2023-05-25 17:31 UTC by jbylund

Copying description from [issue](https://github.com/ArangoDB-Community/python-arango/issues/249):

`pkg_resources` is now deprecated in favor of `importlib.metadata` / `importlib_metadata` ([source](https://setuptools.pypa.io/en/latest/pkg_resources.html)). Right now it causes warnings and in the future (3.12?) I think it will stop working entirely. I saw there was a related [pr](https://github.com/ArangoDB-Community/python-arango/pull/233) but it was using `importlib.metadata` which apparently has different behaviors on some versions of python and caused issues for some users ([ref](https://github.com/ArangoDB-Community/python-arango/issues/244)). Maybe it would be acceptable to use `importlib_metadata` (the backport) either on all versions of python or only when necessary.

2023-05-26 14:21 UTC, apetenchea requested changes

2023-05-26 14:21 UTC, apetenchea commented on tests/test_client.py
> +import importlib_metadata
Thanks for spotting that!

I would be ready to accept this PR, but the pre-commit hook `isort` is failing due to the non-standard ordering of imports. Please see [CONTRIBUTING.md](https://github.com/ArangoDB-Community/python-arango/blob/main/CONTRIBUTING.md) for more details.

2023-05-31 11:07 UTC, jbylund commented
I'm a little worried about the use case of #244 (using without installing via just adding to path). But it seems to work for me:
```
In [5]: import arango

In [6]: arango.__file__
Out[6]: '/Users/joebylund/scratch/python-arango/arango/__init__.py'

In [7]: ArangoClient().version
Out[7]: '7.5.8.dev2+gfac52f3'
```

2023-05-31 17:27 UTC, apetenchea commented
> I'm a little worried about the use case of #244 (using without installing via just adding to path). But it seems to work for me:
> 
> ```
> In [5]: import arango
> 
> In [6]: arango.__file__
> Out[6]: '/Users/joebylund/scratch/python-arango/arango/__init__.py'
> 
> In [7]: ArangoClient().version
> Out[7]: '7.5.8.dev2+gfac52f3'
> ```

That's a valid concern, I'll have to test it out as well. Will get to it by the end of this week.

2023-06-02 14:09 UTC, apetenchea approved these changes
I tried it locally as well and it works for me. However, I am hesitant to merge it yet, without @alexbakharew 's input, as this can potentially affect some of our internal projects.

2023-06-02 15:09 UTC, apetenchea commented
Alright, I talked to @alexbakharew and he confirmed it's working.
Thank you for you contribution!

2023-06-02 15:10 UTC, merged